### ISSUE TITLE
Can't Install in R 3.2 Mac 10.10.3

### ISSUE THREAD

**Issue by alexstaj** [kablag/RDML#17]
> library(devtools)
> install_github("RDML", "kablag")
Downloading github repo kablag/RDML@master
Installing RDML
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/ps/4cns4xzn38z6f9xycv0r8mv00000gn/T/RtmpzlxO38/devtools14ea2dfa9693/kablag-RDML-c67d479'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

* installing *source* package ‘RDML’ ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘rlist’
ERROR: lazy loading failed for package ‘RDML’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/RDML’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/RDML’
Error: Command failed (1)
In addition: Warning message:
Username parameter is deprecated. Please use kablag/RDML

**Comment by kablag** [comment]
Currently github version is unstable and required package 'rlist' wasn't in namespace.
I corrected this and now you can try to install. Or use stable version at CRAN. Cause I need to update docs too. I think I need a week to do this.
