### ISSUE TITLE
Getting documentationError: id is not a 'idType' or length > 1

### ISSUE THREAD

**Issue by kosmoz** [kablag/RDML#18]
Import fails, when the XML has a *documentation* element. My file has the following element and I receive the error message given in the title.

```
	<documentation id="Barcode">
		<text>1234567890</text>
	</documentation>
```

**Comment by kablag** [comment]
Please try to import file with current github version.
Or you can give me file and I'll test it.

**Comment by kosmoz** [comment]
The latest version seems to have an issue with checkmate. I'm getting this error message: 
```
> test <- RDML$new("~/Downloads/1507AA31.rdml")

Loading experiment: Data_Vermeulen_B.xls
	run: HMBS_20080318
Error in RDML$new("~/Downloads/1507AA31.rdml") : 
  Assertion on 'name' failed: Must be of type 'string', not 'NULL'
> 
```
Looks like it tries to assert an unset variable, but the message is not really specific, so I'm not sure where it occurs. I tried with [this file](http://rdmldb.org/download.php?ID=1507AA31) from rdmldb.org, in case you want to look into it.

**Comment by kablag** [comment]
I corrected this issue but got another because 1507AA31.rdml doesn't follow format... I'll ask authors about this.

**Comment by kosmoz** [comment]
Very cool! I know, most of the files on rdmldb.org are invalid. Don't worry about it.

As long as your package works, it would help me a great deal.

**Comment by kablag** [comment]
if it's not a secret: what do you do with my package and what pcr system do you use?
