### ISSUE TITLE
Error in : Some prefixes [d2, d3] don't already exist.

### ISSUE THREAD

**Issue by GA-Goig** [kablag/RDML#21]
Hi
I am working with Roche Lightcycler 96 files. When I open lc96p files straight from the thermal cycler there is no problem importing these files. However, when opening in lightcycler software and saving files either, as lc96p or rdml files, I get an error when importing this files with rdmlEdit(). Browser suddenly closes and R terminal says:

```
Listening on http://127.0.0.1:5267
Warning: Error in : Some prefixes [d2, d3] don't already exist.
Stack trace (innermost first):
    72: xml_ns_rename
    71: GetDilutionsRoche
    70: fromRDML
    69: .subset2(public_bind_env, "initialize")
    68: RDML$new
    67: eval [/home/galo/R/x86_64-pc-linux-gnu-library/3.3/RDML/RDMLedit/server.R#62]
    66: eval
    65: withProgress
    58: isolate
    57: observerFunc [/home/galo/R/x86_64-pc-linux-gnu-library/3.3/RDML/RDMLedit/server.R#54]
     2: shiny::runApp
     1: rdmlEdit
```

Bests

**Comment by kablag** [comment]
Send me your files please

**Comment by GA-Goig** [comment]
I send you 4 files:

RDML_issue_original.lc96p is the original file straight from the thermal cycler. It can be imported with RDML without problems.

The other three can not be opened and always rise the same Error that I wrote above:

RDML_issue_original_saved.lc96p Is the original file opened and saved as .lc96p with not a single modification.

The other two are original files with samples renamed and saves as both, .lc96p and .rdml
[RDML_Issue.zip](https://github.com/kablag/RDML/files/864090/RDML_Issue.zip)


It seems to me that Lightcycler96 software is doing some modifications when saving and that causes the crash. The Lightcycler software version is 1.1.0.1320 and we are running it in a Virtual Box with Windows 10

Thank you very much!

**Comment by kablag** [comment]
Thank you for files.
I made update to resolve your case. Please test new version and report me results.
Lightcycler96 software .lc96p and .rdml files are zip archives that store information in different files.
Problem was that when you save your data Lightcycler96 software creates file with analysis result. When you don't make any analysis it doesn't contain necessary fields...
So new version of RDML can check it.
But it's better to click Analysis inside Lightcycler96 software and make any of them before saving file to avoid another undetected bugs :)

**Comment by GA-Goig** [comment]
Thank you very much!
Now it works nice! 
So interesting they are zip files with xml files within

Hope I finished my analyses and cite this package in our next paper :)

**Comment by kablag** [comment]
All RDML files are xmls inside zip :) For Lightcycler96 software .rdml and .lc96p are the same files.

For citing our package will be presented at qPCR dPCR & NGS 2017 Symposium and maybe article after that. Just for information, look at our article https://journal.r-project.org/archive/2015-1/rodiger-burdukiewicz-blagodatskikh-etal.pdf if you don't read it before ;)
