### ISSUE TITLE
error log messages when loading files on the RDMLedit web-server

### ISSUE THREAD

**Issue by janstrauss1** [kablag/RDML#23]
Dear kablag,

when I load RDML files on the RDMLedit web-server, I see the following log messages
> target: Assertion on 'id' failed: Must be of type 'string', not 'NULL'.
run: Assertion on 'name' failed: Must be of type 'string', not 'NULL'.
react: Assertion on 'id' failed: Must be of type 'string', not 'NULL'.

However, when inspecting the files, they don't appear to be compromised.

Any ideas about these log messages?
Can I simply ignore/clear them?

Thanks in advance,
janstrauss1

**Comment by kablag** [comment]
Just ignore them. It's example of inconsistencies of files and standards.
I.e. Experimenter have to contain name but Bio-Rad leaves this field empty.
Your files are from device or you generate them?

**Comment by janstrauss1** [comment]
Ok. Thanks, that's good to know! 
I generated the files myself using the RDML package.
FYI it also happens when generating and loading files as described in the vignette.
