### ISSUE TITLE
Error 'File not found' when trying to export from RDMLedit web-server

### ISSUE THREAD

**Issue by janstrauss1** [kablag/RDML#24]
Dear kablag,

when I try to export a loaded RDML file from the RDMLedit web-server using `Store RDML`, I get the Firefox error message
> File not found

Thus, I currently don't see a way how use the RDMLedit web-server to modify RDML files.

Any suggestions what could cause the error?

Many thanks in advance,
janstrauss1

**Comment by kablag** [comment]
I'll look at this tomorrow. Thank you for reporting

**Comment by kablag** [comment]
There is an error with time consuming operations inside downloadHandler. Looking for solution.
Local rdmlEdit works fine.
