### ISSUE TITLE
Issues running RDMLedit() locally from Rstudio

### ISSUE THREAD

**Issue by janstrauss1** [kablag/RDML#25]
Dear kablag,

I am trying to run the command `RDMLedit()` locally from a RStudio session.

However, I receive the error

> Listening on http://127.0.0.1:7366
> Warning: Error in library: there is no package called ‘dpcR’
>   52: stop
>   51: library
> Error in library(dpcR) : there is no package called ‘dpcR’

Clearly, I don't have dpcR installed but `install.packages("dpcR")` gives me

> Warning in install.packages :
> package ‘dpcR’ is not available (for R version 3.5.1)

It appears that the ‘dpcR’ package has been removed from the CRAN repository and I wonder if you really need it to run `RDMLedit()` locally?

Many thanks in advance,
janstrauss1

Below my output from `sessionInfo()`

> R version 3.5.1 (2018-07-02)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS High Sierra 10.13.6
> 
> Matrix products: default
> BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] tools     stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] MBmca_0.0.3-5     plotly_4.8.0      ggvis_0.4.3       dplyr_0.7.6       labeling_0.3      ggplot2_3.0.0    
>  [7] withr_2.1.2       crayon_1.3.4      chipPCR_0.0.8-10  RDML_0.9-9        backports_1.1.2   robustbase_0.93-2
> [13] pipeR_0.6.1.3     markdown_0.8      yaml_2.2.0        V8_1.5            shinyjs_1.0       shinythemes_1.1.1
> [19] shiny_1.1.0      
> 
> loaded via a namespace (and not attached):
>  [1] httr_1.3.1         tidyr_0.8.1        jsonlite_1.5       viridisLite_0.3.0  assertthat_0.2.0   Rfit_0.23.0       
>  [7] cellranger_1.1.0   outliers_0.14      pillar_1.3.0       lattice_0.20-35    quantreg_5.36      glue_1.3.0        
> [13] rlist_0.4.6.1      digest_0.6.16      promises_1.0.1     checkmate_1.8.5    colorspace_1.3-2   htmltools_0.3.6   
> [19] httpuv_1.4.5       Matrix_1.2-14      plyr_1.8.4         pkgconfig_2.0.2    SparseM_1.77       purrr_0.2.5       
> [25] xtable_1.8-2       ptw_1.9-13         scales_1.0.0       later_0.7.3        MatrixModels_0.4-1 tibble_1.4.2      
> [31] lazyeval_0.2.1     magrittr_1.5       readxl_1.1.0       mime_0.5           MASS_7.3-50        xml2_1.2.0        
> [37] data.table_1.11.4  stringr_1.3.1      munsell_0.5.0      bindrcpp_0.2.2     compiler_3.5.1     signal_0.7-6      
> [43] rlang_0.2.2        grid_3.5.1         nloptr_1.0.4       htmlwidgets_1.2    gtable_0.2.0       curl_3.2          
> [49] R6_2.2.2           zoo_1.8-3          lubridate_1.7.4    bindr_0.1.1        stringi_1.2.4      parallel_3.5.1    
> [55] Rcpp_0.12.18       DEoptimR_1.0-8     tidyselect_0.2.4   lmtest_0.9-36

**Comment by kablag** [comment]
Try 
```
library(devtools)
install_github("michbur/dpcR")
```
for now. I'll try to remove it from dependencies

**Comment by kablag** [comment]
dpcR removed.
