### ISSUE TITLE
Merge RDML files by exp.id

### ISSUE THREAD

**Issue by janstrauss1** [kablag/RDML#26]
Dear kablag,

I am generating individual RDML files for different qPCR runs (e.g. run1, run2).
The different runs contain samples from the same experiment (e.g. exp1) and I would like to merge individual files by exp.id?

I noticed, however, that RDML currently add's a suffix to the exp.id like in my toy example below instead of merging by identical exp.id
![merged_rdml_dendrogram](https://user-images.githubusercontent.com/28350852/44984296-80697300-af7c-11e8-9fe3-76a3ed3d912f.png)

Is there a way how I could merge by identical exp.id?

Many thanks in advance,
Jan

**Comment by kablag** [comment]
Changed logic
 If experiments or runs have same name they will be combined. Reacts with same id, experiment and run overwrite each other!
